### ISSUE TITLE
pom.xml is obsolete

### ISSUE THREAD

**Issue by nullterminated** [wocommunity/wolips#121]
The maven configuration for wolips still points to svn.objectstyle.org. Also regarding maven, wasn't there a WebObjects maven repo hosted by Apple once long ago? Set up by Pierre. Am I dreaming it? Does it still exist? Is the only way to get WO now in the pkg format?

**Comment by mschrag** [comment]
no longer exists publicly :(

**Comment by nullterminated** [comment]
Good to know I'm not dreaming it :) I do see com.webobjects over at maven.wocommunity.org. That looks like it could work.
