### ISSUE TITLE
Workspace Mechanic?

### ISSUE THREAD

**Issue by witchi** [wocommunity/wolips#128]
How I can get the Google Workspace Mechanic, the Update page is not available.

**Comment by witchi** [comment]
https://alfsch.github.io/eclipse-updates/workspacemechanic

But it produces errors during the software installation.

**Comment by Wolfy42** [comment]
The Google-Mechanic feature is not included in the wolipse-build. Therefore you don't need to to be able to compile it. You can simple close the mechanic-plugin and the mechanic-feature in your eclipse-workspace.

The version of "workspace mechanic" which was used here is quite old and updating it to a current, working version will likely mean a lot of work.

**Comment by nullterminated** [comment]
Workspace mechanic is removed.
