### ISSUE TITLE
Cannot build plugin

### ISSUE THREAD

**Issue by witchi** [wocommunity/wolips#129]
I have added some things to the goodies, but I cannot build it. The Ant process returns

```
Buildfile: /localhome/wolips/wolips/goodies/plugins/org.objectstyle.wolips.goodies.core.linux/build.xml
java:

BUILD FAILED
/localhome/wolips/wolips/goodies/plugins/org.objectstyle.wolips.goodies.core.linux/build.xml:24: The following error occurred while executing this line:
java.io.FileNotFoundException: /localhome/wolips/${project.buildscripts.dir}/plugin-project.xml
```

What is wrong?

**Comment by Wolfy42** [comment]
The variable "project.buildscripts.dir" is set to the value "buildscripts" in the default.properties located in the top directory. The build of wolips is configured to be started at the top directory (see readme). It you don't start the build there, then the variable will not be set.

If you want to build just your new plugin you could try to add the value for the variable with the ant-call ("-Dproject.buildscripts.dir=" ...). But I think it would be easier to build the complete wolips-project.

**Comment by nullterminated** [comment]
This is much easier to build now :)

git clone -b wolips5 https://github.com/wocommunity/wolips.git wolips5
cd wolips5
mvn clean package
