### ISSUE TITLE
EntityModeler does not play nice with Eclipe 21.03

### ISSUE THREAD

**Issue by johanhenselmans** [wocommunity/wolips#154]
Had to update an old project, and, seeing that WOLips was fixed for Eclipse 20.09, tried to run entity modeler. 

No dice. It opened a window, that was it. Then I tried Eclipse 20.09R, and I could not create an eomodel nor edit an eomodel. 

I have'nt the faintest idea how to debug this, but I would be happy to lend a hand testing if someone is up for a challenge.

**Comment by nullterminated** [comment]
Hi Johan, there have been some fixes to the eomodeler lately. Have you had a chance to try again with the latest build on jenkins?

https://jenkins.wocommunity.org/job/WOLips_master/lastSuccessfulBuild/artifact/

There was an issue with modeler when using a modular JDK (9+) that may have caused this.
