### ISSUE TITLE
Updating Eclipse 2023-06 (4.27 -> 4.28) breaks WOLips

### ISSUE THREAD

**Issue by galmok** [wocommunity/wolips#174]
I just updated Eclipse 2023-06 with the latest updates and this breaks WOLips.

The Related window is completely gone and reports this exception:

org.eclipse.core.runtime.CoreException: Plug-in "org.objectstyle.wolips.ui" was unable to instantiate class "org.objectstyle.wolips.ui.view.RelatedView".
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:212)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:206)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	...

Opening a component reports this exception (it does show a very small view of the HTML and WOD files):

java.lang.NoClassDefFoundError: org/eclipse/ui/views/navigator/LocalSelectionTransfer
	at org.objectstyle.wolips.componenteditor.part.ComponentEditor.initializeDragAndDrop(ComponentEditor.java:194)
	at org.objectstyle.wolips.componenteditor.part.ComponentEditor.createPages(ComponentEditor.java:177)
	at org.eclipse.ui.part.MultiPageEditorPart.createPartControl(MultiPageEditorPart.java:333)
	...

As it is now, WOLips isn't working well enough to be used. I will reinstall Eclipse 2023-06 (if downgrading it isn't possible; never tried) and avoid updating it.

I am using WOLips from:

https://jenkins.wocommunity.org/job/WOLips_master/lastSuccessfulBuild/artifact/temp/dist/

Eclipse version: 2023-06 (4.28.0)
Build id: 20230608-1333

Current installation:

    Buildship: Eclipse Plug-ins for Gradle	3.1.7.v20230428-1350
    Bytecode Outline View	1.2.0.v20230323-1830
    EclEmma Java Code Coverage	3.1.7.202306070845
    Eclipse IDE for Java Developers	4.28.0.20230608-1200
    Eclipse Java Development Tools	3.19.100.v20230605-0440
    Eclipse Platform	4.28.0.v20230605-0440
    Eclipse RCP	4.28.0.v20230605-0440
    Enhanced Class Decompiler (Core)	3.3.0
    Enhanced Class Decompiler CFR Extension (Optional)	3.3.0
    Enhanced Class Decompiler JD-Core Extension (Optional)	3.3.0
    Enhanced Class Decompiler Procyon Extension (Optional)	3.3.0
    Enhanced Class Decompiler Quiltflower Extension (Optional)	3.3.0
    Enhanced Class Decompiler Source (Optional)	3.3.0
    Git integration for Eclipse	6.6.0.202305301015-r
    Java implementation of Git	6.6.0.202305301015-r
    JustJ Adoptium OpenJDK Hotspot JRE Complete	20.0.1.v20230425-1611
    M2E - Maven Integration for Eclipse	2.3.0.20230523-2033
    M2E - POM Editor using LemMinX language server (includes Incubating components)	2.0.4.20230520-0934
    M2E - SLF4J over Logback Logging	2.1.2.20230523-2106
    Marketplace Client	1.10.1.v20221110-1841
    Mylyn WikiText	3.0.46.202301111837
    Oomph Setup	1.28.0.v20230523-0636
    Tip of the Day UI Feature	0.4.0.v20230429-1617
    TM Terminal	11.2.0.202303131754
    Wild Web Developer XML tools	1.1.0.202304242122
    WOLips	4.18.20230108.17
    ZipEditor	1.1.8.202010020827

Previous installation:

    Buildship: Eclipse Plug-ins for Gradle	3.1.6.v20220511-1359
    Bytecode Outline View	1.1.0.v20230117-1348
    EclEmma Java Code Coverage	3.1.6.202206011447
    Eclipse IDE for Java Developers	4.27.0.20230309-1200
    Eclipse Java Development Tools	3.19.0.v20230302-0300
    Eclipse Platform	4.27.0.v20230302-0300
    Eclipse RCP	4.27.0.v20230302-0300
    Enhanced Class Decompiler (Core)	3.3.0
    Enhanced Class Decompiler CFR Extension (Optional)	3.3.0
    Enhanced Class Decompiler JD-Core Extension (Optional)	3.3.0
    Enhanced Class Decompiler Procyon Extension (Optional)	3.3.0
    Enhanced Class Decompiler Quiltflower Extension (Optional)	3.3.0
    Enhanced Class Decompiler Source (Optional)	3.3.0
    Git integration for Eclipse	6.5.0.202303070854-r
    Java implementation of Git	6.5.0.202303070854-r
    JustJ Adoptium OpenJDK Hotspot JRE Complete	20.0.1.v20230425-1611
    M2E - Maven Integration for Eclipse	2.2.1.20230307-1553
    M2E - POM Editor using LemMinX language server (includes Incubating components)	2.0.3.20230202-1631
    M2E - SLF4J over Logback Logging	2.1.1.20230106-1511
    Marketplace Client	1.10.1.v20221110-1841
    Mylyn WikiText	3.0.46.202301111837
    Oomph Setup	1.28.0.v20230429-0905
    Tip of the Day UI Feature	0.3.100.v20230109-1247
    TM Terminal	11.1.0.202212091724
    Wild Web Developer XML tools	1.0.2.202301201156
    WOLips	4.18.20230108.17
    ZipEditor	1.1.8.202010020827

**Comment by galmok** [comment]
Ah, I tried to revert, but it reverted to the 2023-03 release and didn't just undo the updates I had just installed. I hope I can rescue this installation...

**Comment by hugithordarson** [comment]
This was fixed in 2eca954c5ea9337073c8746be6715758ff487896
